# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agented < Formula
  desc "Stateful, persistent text editor for LLM agents (verb-based, SQLite undo tree)."
  homepage "https://github.com/frane/agented"
  version "0.3.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frane/agented/releases/download/v0.3.7/agented_0.3.7_darwin_x86_64.tar.gz"
      sha256 "9dec33efff2a0e4e994d59fb05b6e317b097bfb6c312f80ed11553fda00cd46f"

      define_method(:install) do
        bin.install "ae"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frane/agented/releases/download/v0.3.7/agented_0.3.7_darwin_arm64.tar.gz"
      sha256 "c71d1fd1551506c215f25a50349667b6f59eac61972c3e83f1925f98a9643680"

      define_method(:install) do
        bin.install "ae"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frane/agented/releases/download/v0.3.7/agented_0.3.7_linux_x86_64.tar.gz"
      sha256 "038fe91cd0cbc86695e6b98e3d8d56fc1fe5817d70f65e8b4315c138c1773bd2"
      define_method(:install) do
        bin.install "ae"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frane/agented/releases/download/v0.3.7/agented_0.3.7_linux_arm64.tar.gz"
      sha256 "6f45f70d7bcdb1d61b0734f48eedb16887f62bc53cb22209845f58abadc40652"
      define_method(:install) do
        bin.install "ae"
      end
    end
  end

  def caveats
    <<~EOS
      ae is a stateful editor for LLM agents. After install, run:
        ae skill install
      to drop the SKILL.md into your Claude/Codex/Cursor skills directory.
    EOS
  end

  test do
    assert_match "ae version", shell_output("#{bin}/ae --version")
  end
end
