# This file was generated by GoReleaser. DO NOT EDIT.
cask "agented" do
  version "0.4.9"

  on_macos do
    on_intel do
      sha256 "499f5abb7e9b5378d811c614f41c4d4294e12665f52fff7a89a92cd2777279c9"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/frane/agented"
    end
    on_arm do
      sha256 "d158ae2981a9e434b50c6f150ab30e30f5ce0b119bdb9077c63bd3de31dc440e"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/frane/agented"
    end
  end

  on_linux do
    on_intel do
      sha256 "269099a5c0e96893d1c13bf30a7f775f1155d5588abb946a2314ab5c3c345790"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/frane/agented"
    end
    on_arm do
      sha256 "ba2c696a13a7eb213ca1789d2cd1f73b326b8a7a8dee723b931f7a40e6f11f71"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_linux_arm64.tar.gz",
        verified: "github.com/frane/agented"
    end
  end

  name "agented"
  desc "A text editor for LLMs, not humans."
  homepage "https://github.com/frane/agented"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ae"

  postflight do
    if OS.mac?
      # Release tarballs are not codesigned. Strip the quarantine xattr
      # so macOS Sequoia Gatekeeper does not SIGKILL the binary on first
      # invocation. See https://github.com/frane/agented v0.3.6 notes.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ae"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ae is a stateful editor for LLM agents. After install, run:
      ae skill install
    to drop the SKILL.md into your Claude/Codex/Cursor skills directory.
  EOS
end
