# This file was generated by GoReleaser. DO NOT EDIT.
cask "agented" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "10a75f776e177f59f75307a50e65cb3e639ee3f7c2e2804df39ef994a05d8aab"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/frane/agented"
    end
    on_arm do
      sha256 "a96988d0e776ec9149591fb57053bf9317f3584b5c9564e18d91958a9e5a7448"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/frane/agented"
    end
  end

  on_linux do
    on_intel do
      sha256 "4620a30cc1c0ae7daccfac6a121fda9029220f76e3cd52a1b366485bcf0350cb"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/frane/agented"
    end
    on_arm do
      sha256 "d6a80731a038e47707cf6e2914d06f0ded21dafa5a511e6273dc2e0e758003c7"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_linux_arm64.tar.gz",
        verified: "github.com/frane/agented"
    end
  end

  name "agented"
  desc "A text editor for LLMs, not humans."
  homepage "https://github.com/frane/agented"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ae"

  postflight do
    if OS.mac?
      # Release tarballs are not codesigned. Strip the quarantine xattr
      # so macOS Sequoia Gatekeeper does not SIGKILL the binary on first
      # invocation. See https://github.com/frane/agented v0.3.6 notes.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ae"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ae is a stateful editor for LLM agents. After install, run:
      ae skill install
    to drop the SKILL.md into your Claude/Codex/Cursor skills directory.
  EOS
end
