# This file was generated by GoReleaser. DO NOT EDIT.
cask "agented" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "34dabb4d80aee6e4dbb93d69317a60d43ed312376ab40423ca8deb30b9ee5005"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/frane/agented"
    end
    on_arm do
      sha256 "43d09266be5aee43569c0a0b069391c81141647140eaa75f985f3f6bc3f6bc99"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/frane/agented"
    end
  end

  on_linux do
    on_intel do
      sha256 "5d282f38bd1b69844be9a82c16f19561228db7f16fc104fffa0e3497c13294fe"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/frane/agented"
    end
    on_arm do
      sha256 "6c0fb41ee8b40b7a2285af4e79ba99cac4c2bc175f0321b2bfe2566359f4b445"
      url "https://github.com/frane/agented/releases/download/v#{version}/agented_#{version}_linux_arm64.tar.gz",
        verified: "github.com/frane/agented"
    end
  end

  name "agented"
  desc "A text editor for LLMs, not humans."
  homepage "https://github.com/frane/agented"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ae"

  postflight do
    if OS.mac?
      # Release tarballs are not codesigned. Strip the quarantine xattr
      # so macOS Sequoia Gatekeeper does not SIGKILL the binary on first
      # invocation. See https://github.com/frane/agented v0.3.6 notes.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ae"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ae is a stateful editor for LLM agents. After install, run:
      ae skill install
    to drop the SKILL.md into your Claude/Codex/Cursor skills directory.
  EOS
end
